CREATE TABLE [core].[ContactDetail] (
    [Id]                         INT            IDENTITY (1, 1) NOT NULL,
    [Timestamp]                  ROWVERSION     NOT NULL,
    [StatusId]                   INT            NOT NULL,
    [CreatedByUserProfileId]     INT            NOT NULL,
    [LastUpdatedByUserProfileId] INT            NOT NULL,
    [CreatedOn]                  DATETIME       NOT NULL,
    [LastUpdatedOn]              DATETIME       NOT NULL,
    [ValidFrom]                  DATETIME       NOT NULL,
    [ValidTo]                    DATETIME       NOT NULL,
    [ContractId]                 INT            NULL,
    [ParentContactId]            INT            NULL,
    [ContactTypeId]              INT            NULL,
    [ShortName]                  NVARCHAR (50)  NULL,
    [DisplayName]                NVARCHAR (450) NULL,
    [LegalName]                  NVARCHAR (450) NULL,
    [BuildingName]               NVARCHAR (250) NULL,
    [Street1]                    NVARCHAR (250) NULL,
    [Street2]                    NVARCHAR (250) NULL,
    [Town]                       NVARCHAR (250) NULL,
    [County]                     NVARCHAR (250) NULL,
    [PostCode]                   NVARCHAR (25)  NULL,
    [NationalRegionId]           INT            NULL,
    [CountryId]                  INT            NULL,
    [Telephone1]                 NVARCHAR (50)  NULL,
    [Telephone2]                 NVARCHAR (50)  NULL,
    [EmailAddress]               NVARCHAR (320) NULL,
    CONSTRAINT [PK_CORE_ContactDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ContactDetail_ContactType] FOREIGN KEY ([ContactTypeId]) REFERENCES [core].[ContactType] ([Id]),
    CONSTRAINT [FK_ContactDetail_Contract] FOREIGN KEY ([ContractId]) REFERENCES [core].[Contract] ([Id]),
    CONSTRAINT [FK_ContactDetail_Country] FOREIGN KEY ([CountryId]) REFERENCES [core].[Country] ([Id]),
    CONSTRAINT [FK_ContactDetail_CreatedByUserProfile] FOREIGN KEY ([CreatedByUserProfileId]) REFERENCES [sec].[UserProfile] ([Id]),
    CONSTRAINT [FK_ContactDetail_LastUpdatedByUserProfile] FOREIGN KEY ([LastUpdatedByUserProfileId]) REFERENCES [sec].[UserProfile] ([Id]),
    CONSTRAINT [FK_ContactDetail_NationalRegion] FOREIGN KEY ([NationalRegionId]) REFERENCES [core].[NationalRegion] ([Id]),
    CONSTRAINT [FK_ContactDetail_ParentContactDetail] FOREIGN KEY ([ParentContactId]) REFERENCES [core].[ContactDetail] ([Id]),
    CONSTRAINT [FK_ContactDetail_Status] FOREIGN KEY ([StatusId]) REFERENCES [core].[Status] ([Id])
);

