CREATE TABLE [core].[Country] (
    [Id]                         INT              IDENTITY (1, 1) NOT NULL,
    [Timestamp]                  ROWVERSION       NOT NULL,
    [StatusId]                   INT              NOT NULL,
    [CreatedByUserProfileId]     INT              NOT NULL,
    [LastUpdatedByUserProfileId] INT              NOT NULL,
    [CreatedOn]                  DATETIME         NOT NULL,
    [LastUpdatedOn]              DATETIME         NOT NULL,
    [ValidFrom]                  DATETIME         NOT NULL,
    [ValidTo]                    DATETIME         NOT NULL,
    [IsoCode]                    NVARCHAR (10)    NULL,
    [AbbreviatedName]            NVARCHAR (50)    NULL,
    [FullName]                   NVARCHAR (250)   NULL,
    [NativeName]                 NVARCHAR (250)   NULL,
    [DialingCode]                NVARCHAR (10)    NULL,
    [PostCodeFormat]             NVARCHAR (100)   NULL,
    [CurrencyId]                 INT              NULL,
    [LanguageId]                 INT              NULL,
    [TimeZoneId]                 INT              NULL,
    [WorldRegionId]              INT              NULL,
    [ImageTypeId]                INT              NULL,
    [CountryFlag]                VARBINARY (2048) NULL,
    CONSTRAINT [PK_CORE_Country] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Country_CreatedByUserProfile] FOREIGN KEY ([CreatedByUserProfileId]) REFERENCES [sec].[UserProfile] ([Id]),
    CONSTRAINT [FK_Country_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [core].[Currency] ([Id]),
    CONSTRAINT [FK_Country_Language] FOREIGN KEY ([LanguageId]) REFERENCES [core].[Language] ([Id]),
    CONSTRAINT [FK_Country_LastUpdatedByUserProfile] FOREIGN KEY ([LastUpdatedByUserProfileId]) REFERENCES [sec].[UserProfile] ([Id]),
    CONSTRAINT [FK_Country_Status] FOREIGN KEY ([StatusId]) REFERENCES [core].[Status] ([Id]),
    CONSTRAINT [FK_Country_TimeZone] FOREIGN KEY ([TimeZoneId]) REFERENCES [core].[Timezone] ([Id]),
    CONSTRAINT [FK_Country_WorldRegion] FOREIGN KEY ([WorldRegionId]) REFERENCES [core].[WorldRegion] ([Id])
);

