DELETE FROM [app].[MenuItem]
SET IDENTITY_INSERT [app].[MenuItem] ON 
GO

-- Application Ids
-- 0 = Core System
-- 1 = JDV Software
-- 3 = National Lottery

/* Core System */

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (100, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, null, 'Development',                  'Development',          null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (101, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 100,  'BasicControlsForm',            'Basic Controls Form',              'Foundation.Interfaces', 'Foundation.Interfaces.IBasicControlsViewModel',               'Foundation.Views', 'Foundation.Views.Test.BasicControlsView',  'A demonstrator form for the Basic Controls of WPF', 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (102, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 100,  'Test Form',                    'Test Form',                        'Foundation.Interfaces', 'Foundation.Interfaces.ITestFormViewModel',                    'Foundation.Views', 'Foundation.Views.Test.TestForm',           'Popup test form',                      0, 1, null);

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (200, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, null, 'CoreReferenceData',            'Core Reference Data',  null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (201, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 200,  'MenuItems',                    'Menu Items',                       'Foundation.Interfaces', 'Foundation.Interfaces.IMenuItemViewModel',                    'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Menu Items',                  0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (202, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 200,  'Contact',                      'Contacts',                         'Foundation.Interfaces', 'Foundation.Interfaces.IContactDetailViewModel',               'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Contacts',                    0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (203, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 200,  'Contract',                     'Contracts',                        'Foundation.Interfaces', 'Foundation.Interfaces.IContractViewModel',                    'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Contracts',                   0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (204, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 200,  'Office',                       'Offices',                          'Foundation.Interfaces', 'Foundation.Interfaces.IOfficeViewModel',                      'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Offices',                     0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (205, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 200,  'ApplicationConfiguration',     'Application Configurations',       'Foundation.Interfaces', 'Foundation.Interfaces.IApplicationConfigurationViewModel',    'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Application Configurations',  0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (206, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 200,  'ScheduledJobs',                'Scheduled Jobs',                   'Foundation.Interfaces', 'Foundation.Interfaces.IScheduledJobViewModel',                'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Scheduled Jobs',              0, 1, null);

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (300, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, null, 'CoreStaticData',               'Core Static Data',     null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (301, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'ContractType',                 'Contract Types',                   'Foundation.Interfaces', 'Foundation.Interfaces.IContractTypeViewModel',                'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Contract Types',              0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (302, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'Country',                      'Countries',                        'Foundation.Interfaces', 'Foundation.Interfaces.ICountryViewModel',                     'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Countries',                   0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (303, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'Currency',                     'Currencies',                       'Foundation.Interfaces', 'Foundation.Interfaces.ICurrencyViewModel',                    'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Currencies',                  0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (304, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'Department',                   'Departments',                      'Foundation.Interfaces', 'Foundation.Interfaces.IDepartmentViewModel',                  'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Departments',                 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (305, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'NationalRegion',               'National Regions',                 'Foundation.Interfaces', 'Foundation.Interfaces.INationalRegionViewModel',              'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all National Regions',            0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (306, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'NonWorkingDays',               'Non-Working Days',                 'Foundation.Interfaces', 'Foundation.Interfaces.INonWorkingDayViewModel',               'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Non-Working Days',            0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (307, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'OfficeWeekCalendar',           'Office Week Calendar',             'Foundation.Interfaces', 'Foundation.Interfaces.IOfficeWeekCalendarViewModel',          'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Office Week Calendars',       0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (308, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 300,  'WorldRegion',                  'World Regions',                    'Foundation.Interfaces', 'Foundation.Interfaces.IWorldRegionViewModel',                 'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all World Regions',               0, 1, null);

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (400, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, null, 'Logs',                         'Logs',                 null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (401, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 400,  'ImportExportControl',          'Import/Export Control',            'Foundation.Interfaces', 'Foundation.Interfaces.IImportExportControlViewModel',         'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Import Export Control logs',  0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (402, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 400,  'EventLog',                     'Event Log',                        'Foundation.Interfaces', 'Foundation.Interfaces.IEventLogViewModel',                    'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Event Logs',                  0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (403, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 400,  'EventLogApplications',         'Event Log Applications',           'Foundation.Interfaces', 'Foundation.Interfaces.IEventLogApplicationViewModel',         'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Event Log Applications',      0, 1, null);

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (500, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, null, 'ecurity',                      'Security',             null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (501, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'Applications',                 'Applications',                     'Foundation.Interfaces', 'Foundation.Interfaces.IApplicationViewModel',                 'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Applications',                0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (502, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'ApplicationTypesMapping',      'Application Types Mapping',        'Foundation.Interfaces', 'Foundation.Interfaces.IApplicationApplicationTypeViewModel',  'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Application Types Mappings',  0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (503, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'ApplicationRoles',             'Application Roles',                'Foundation.Interfaces', 'Foundation.Interfaces.IApplicationRoleViewModel',             'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Application Roles',           0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (504, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'ApplicationTypes',             'Application Types',                'Foundation.Interfaces', 'Foundation.Interfaces.IApplicationTypeViewModel',             'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Application Types',           0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (505, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'ApplicationUserRolesMapping',  'Application User Roles Mapping',   'Foundation.Interfaces', 'Foundation.Interfaces.IApplicationUserRoleViewModel',         'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Application User Roles',      0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (506, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'Roles',                        'Roles',                            'Foundation.Interfaces', 'Foundation.Interfaces.IRoleViewModel',                        'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Roles',                       0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (507, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'UserProfiles',                 'User Profiles',                    'Foundation.Interfaces', 'Foundation.Interfaces.IUserProfileViewModel',                 'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all User Profiles',               0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (508, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'PermissionsMatrix',            'Permissions Matrix',               'Foundation.Interfaces', 'Foundation.Interfaces.IPermissionMatrixViewModel',            'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Permission Matrices',         0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (509, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 500,  'ActiveDirectoryUsers',         'Active Directory User',            'Foundation.Interfaces', 'Foundation.Interfaces.IActiveDirectoryUserViewModel',         'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Active Directory Users',      0, 1, null);

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (600, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, null, 'SystemStaticData',             'System Static Data',   null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (601, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'ApprovalStatus',               'Approval Status',                  'Foundation.Interfaces', 'Foundation.Interfaces.IApprovalStatusViewModel',              'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Approval Statuses',           0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (602, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'ConfigurationScope',           'Configuration Scope',              'Foundation.Interfaces', 'Foundation.Interfaces.IConfigurationScopeViewModel',          'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Configuration Scopes',        0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (603, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'ContactType',                  'Contact Types',                    'Foundation.Interfaces', 'Foundation.Interfaces.IContactTypeViewModel',                 'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Contact Types',               0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (604, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'DataStatus',                   'Data Statuses',                    'Foundation.Interfaces', 'Foundation.Interfaces.IDataStatusViewModel',                  'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Data Statuses',               0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (605, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'EntityStatus',                 'Entity Statuses',                  'Foundation.Interfaces', 'Foundation.Interfaces.IEntityStatusViewModel',                'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Entity Statuses',             0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (606, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'ImageType',                    'Image Type',                       'Foundation.Interfaces', 'Foundation.Interfaces.IImageTypeViewModel',                   'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Image Types',                 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (607, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'Language',                     'Languages',                        'Foundation.Interfaces', 'Foundation.Interfaces.ILanguageViewModel',                    'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Languages',                   0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (608, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'LogSeverity',                  'Log Severity',                     'Foundation.Interfaces', 'Foundation.Interfaces.ILogSeverityViewModel',                 'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Log Severities',              0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (609, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'ScheduleIntervalTypes',        'Schedule Interval Types',          'Foundation.Interfaces', 'Foundation.Interfaces.IScheduleIntervalViewModel',            'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Schedule Interval Types',     0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (610, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'Status',                       'Statuses',                         'Foundation.Interfaces', 'Foundation.Interfaces.IStatusViewModel',                      'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Statuses',                    0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (611, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 600,  'TimeZone',                     'Time Zones',                       'Foundation.Interfaces', 'Foundation.Interfaces.ITimeZoneViewModel',                    'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Time Zones',                  0, 1, null);


INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (900, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, null, 'MenuDemoRoot1',                'Menu Demo Root 1',     null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (901, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 900,  'MenuItem1',                    'Menu item 1',                      'Foundation.Interfaces', 'Foundation.Interfaces.IApprovalStatusViewModel',              'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Approval Statuses',           0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (910, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 900,  'MenuDemoRoot2',                'Menu Demo Root 2',     null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (911, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 0, 910,  'MenuItem2',                    'Menu item 2',                      'Foundation.Interfaces', 'Foundation.Interfaces.IApprovalStatusViewModel',              'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View all Approval Statuses',           0, 1, null);


/* JDV Accounts */

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (1000, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 1, null,  'JDV Accounts',               'JDV Accounrs',         null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (1001, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 1, 1000,  'AccountTransactions',        'Account Transactions',             'Foundation.Interfaces', 'Foundation.Interfaces.IAccountTransactions',                  'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View Account Transactions',            0, 1, null);

/* National Lottery */

INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (3000, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 3, null,  'National Lottery',           'National Lottery',     null, null, null, null, null, 0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (3001, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 3, 3000,  'EuroMillions',               'Euro Millions',                    'Foundation.Interfaces', 'Foundation.Interfaces.IEuroMillionsNumbersViewModel',         'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View Euro Millions results',           0, 1, null);
INSERT INTO app.MenuItem ([Id], [StatusId], [CreatedByUserProfileId], [LastUpdatedByUserProfileId], [CreatedOn], [LastUpdatedOn], [ValidFrom], [ValidTo], [ApplicationId], [ParentMenuItemId], [Name], [Caption], [ControllerAssembly], [ControllerType], [ViewAssembly], [ViewType], [HelpText], [MultiInstance], [ShowInTab], [Icon]) VALUES (3002, 0, 1, 1, '2000-01-01', '2000-01-01', '2000-01-01', '2199-12-31T23:59:59', 3, 3000,  'Lotto',                      'Lotto',                            'Foundation.Interfaces', 'Foundation.Interfaces.ILottoNumbersViewModel',                'Foundation.Views', 'Foundation.Views.GenericDataGridView',     'View Lotto Results',                   0, 1, null);
